version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt

  build:
    commands:
      - pytest || exit 1

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - '**/*'
